### ISSUE TITLE
Thêm api cho phép lưu lại một số sự kiện nghiệm trọng của hệ thống scada

### ISSUE THREAD

**Issue by truonganhhoang** [tran-the-lam/scada-project#2]
tham khảo https://chat.openai.com/share/39d7e46a-b637-4f40-9aa5-70498ca50117

**Comment by tran-the-lam** [comment]
Em đang nghĩ tới là sẽ làm lưu thông tin của những lần cảm biến đó được các chỉ số (nhiệt độ, áp suất) vượt ngưỡng giới hạn
Ví dụ mẫu JSON lưu trên Hyperledger Fabric:
```
{
   "event": "limit_exceeded",
   "sensor_id": "ABC123",
   "parameter": "temperature", // tham số vượt ngưỡng
   "value": 40.0, // Gía trị trên cảm biến
   "threshold": 35.0, // Giá trị an toàn được thiết lập
   "timestamp": 1694861094012 // Thời gian ghi nhận
}
```

Đồng thời, project sẽ bổ sung thêm api `post` để đẩy dữ liệu khi cảm biến đo được các chỉ số vượt mức giới hạn và api `get` để lọc các sự kiện theo range timestamp. Các chỉ số giới hạn sẽ được thiết lập sẵn `env` ở Backend. Demo ứng dụng sẽ thêm một màn hình hiển thị lịch sử(cho phép filter theo thời gian, loại chỉ số, sensor_id) những sự kiện vượt quá ngưỡng an toàn. Thầy cho em xin ý kiến với ạ.

**Comment by truonganhhoang** [comment]
Nên để tổng quát họ muốn lưu json gì cũng đc..

**Comment by tran-the-lam** [comment]
Vâng, việc mình lưu vào Fabric thì em vẫn sẽ lưu dưới dạng stringify nhưng trong phần demo thì mình nên phải define ra 1 struct cụ thể vì còn phần tìm kiếm theo các thuộc tính nữa ạ. Em đang hiểu như thế ạ

**Comment by truonganhhoang** [comment]
Ok em..
