### ISSUE TITLE
trường hợp lưu blockchain dữ liệu thông số

### ISSUE THREAD

**Issue by HPM6789** [tran-the-lam/scada-project#24]
[trường hợp lưu blockchain dữ liệu thông số.docx](https://github.com/tran-the-lam/scada-project/files/14092655/tr.ng.h.p.l.u.blockchain.d.li.u.thong.s.docx)

Gửi anh Lâm

**Comment by tran-the-lam** [comment]
Hi @HPM6789, bạn có thể mô tả rõ hơn giúp mình được không? Khi nào cần thông số này và nó được dùng ở đâu.

**Comment by pccong** [comment]
Mô tả giống comment mà. Các trường dữ liệu cần được lưu như ở các struct là ParameterEvent, AlarmEvent và UserEvent. Đối với một hệ thống SCADA: 

+các dữ liệu quá trình của một công đoạn quan trọng nào đó (có thể lấy từ sensor, trạng thái điều khiển, v.v) cần được lưu lại. Các trường dữ liệu giống như ở ParameterEvent. Do hệ thống SCADA tự động lưu.
+mỗi khi xẩy ra cảnh báo thì thông tin về cảnh báo sẽ được hệ thống SCADA lưu tự động vào blockchain. struct là AlarmEvent.
+khi người dùng ở hệ thống SCADA thay đổi thông số cấu hình (tham số công nghệ của hệ thống, chẳng hạn điều chỉnh lượng than cấp vào hệ thống điều khiển lò hơi) thì các thông tin cấu hình này cũng cần được lưu lại.  struct là UserEvent.

**Comment by HPM6789** [comment]
mình test api bằng tay trên postman thôi
