### ISSUE TITLE
Get Event, Get User, Get History Login Issue

### ISSUE THREAD

**Issue by HPM6789** [tran-the-lam/scada-project#25]
Nếu không có dữ liệu api sẽ báo lỗi và tự động tắt

**Comment by tran-the-lam** [comment]
Có thể mô tả cho em rõ hơn về tưng step được không. Input là gì, step là gì, expected output là gì

**Comment by HPM6789** [comment]
trường hợp api get users khi chưa có dữ liệu
postman báo không kết nối được
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/d76ba2de-0eb8-4864-a99a-9e1e1cf53aae)

console báo lỗi rồi tắt api
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/c4739d17-e50c-4b20-a5d7-77284b9c51fc)
*note nghĩ là do câu lệnh panic
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/e1076067-5960-45cf-b6f0-0e3012df910c)

**Comment by tran-the-lam** [comment]
@HPM6789 Bạn sinh năm bao nhiêu nhỉ, để mình tiện giao tiếp

**Comment by HPM6789** [comment]
em 97 ạ

**Comment by tran-the-lam** [comment]
Mình cũng Đinh Sửu :D

**Comment by tran-the-lam** [comment]
Bạn check ở commit này nhé https://github.com/tran-the-lam/scada-project/commit/854b7ca6ea37b140483014a0700d155aba21c473

**Comment by HPM6789** [comment]
ok bạn

**Comment by HPM6789** [comment]
Đang tiện tay sửa thì bạn sửa luôn cái struct Event như thế này đươc ko? :v
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/316b988e-41c9-4eeb-ade7-d896d45831a1)
(đổi tên sensor_id thành parameter_id, cái này thì thầy Hoàng với thấy Công thống nhất vs nhau r)

**Comment by tran-the-lam** [comment]
Mình chưa sửa được, cái này liên quan nhiều đến code UI của mình

**Comment by HPM6789** [comment]
Lúc nào bạn sửa thì báo cho mình nhé

**Comment by tran-the-lam** [comment]
Bạn check code mới nhất ở nhánh này nhé https://github.com/tran-the-lam/scada-project/tree/feat/kc

**Comment by HPM6789** [comment]
Mình add event thì lúc Get All Event không hiện giá trị của parameter_id.
Add event
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/7d83b8ca-3035-42c5-960c-33e2c389eefb)
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/ed8142e3-51a9-4c9c-91cb-28b272552a5c)
