### ISSUE TITLE
Get History Change Password Issue

### ISSUE THREAD

**Issue by HPM6789** [tran-the-lam/scada-project#26]
đã đổi password nhưng api trả về message success nhưng dữ liệu không chứa thông tin các lần đổi password

**Comment by tran-the-lam** [comment]
Nhưng dữ liệu không chứa các thông tin đổi password là sao anh nhỉ. Có thể mô tả rõ hơn test case từng step được không ạ

**Comment by HPM6789** [comment]
Em đổi password của admin thành 123456
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/96b61e79-1ed4-4642-92e1-e858054416d8)
Lịch sử đổi password của admin khi gọi api này thì nó không trả về thông tin các lần đổi password
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/10511197-0618-4a25-bfea-fc4e233afb65)

**Comment by tran-the-lam** [comment]
Bạn check code ở nhánh này nhé https://github.com/tran-the-lam/scada-project/tree/feat/kc

**Comment by HPM6789** [comment]
Url có thay đổi gì không bạn? Mình test bị lỗi 500
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/2a7a42e3-2324-4e47-8994-a6d03bfa1188)

**Comment by tran-the-lam** [comment]
clear data, deploy lại smc đi bạn

**Comment by tran-the-lam** [comment]
SMC có thay đổi nên bạn cần phải deploy lại smc, rồi bạn test lại cả mấy case bạn vừa báo nhé

**Comment by HPM6789** [comment]
mình clear data và smc rồi vẫn bị vậy

**Comment by tran-the-lam** [comment]
Bạn clear như thế nào. Các step cụ thể là gì

**Comment by HPM6789** [comment]
mình vào fabric-samples/test-network, gõ ./network.sh down

**Comment by tran-the-lam** [comment]
Chắc do mình commit thiếu. Bạn pull lại code, rồi thử lại nhé

**Comment by HPM6789** [comment]
Hết lỗi rồi bạn. Bạn merge vào main xong thì close issue để confirm nhé :v

**Comment by HPM6789** [comment]
cái này là lỗi bên mình
