### ISSUE TITLE
Get State vẫn lấy được dữ liệu của user đã bị xóa

### ISSUE THREAD

**Issue by HPM6789** [tran-the-lam/scada-project#27]
Get State vẫn lấy được dữ liệu của user đã bị xóa

**Comment by tran-the-lam** [comment]
Là bạn gọi api nào nhỉ, còn phần user, mình nhớ là đã xử lý rồi. Nếu được mô tả rõ hơn giúp mình với nhé

**Comment by HPM6789** [comment]
Trong list users có user_id = 2
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/bacc45f5-0166-41b2-a3e7-cadc4f39e884)
Sau đó xóa user đó đi
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/075f27a2-4f4e-4bf0-bebd-ba73a79b7607)
Sau đó vẫn get được
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/4654fc0f-dd49-463d-8985-202928c928fb)

**Comment by tran-the-lam** [comment]
Cái key đó mình sẽ vẫn luôn lưu để trace lại, còn việc get list user mà vẫn ra 2 thì đó là bug, nhưng như mình test lại thì thấy không có bug đấy. Không biết bạn đã pullcode mới về chạy chưa

**Comment by HPM6789** [comment]
list thì không còn bug đó nữa.
Tại vì ban đầu mình nghĩ là GetState nó không get được cái bị xóa, api này để nguyên vậy nhé.
