### ISSUE TITLE
Add User đã tồn tại trong hệ thống Issue

### ISSUE THREAD

**Issue by HPM6789** [tran-the-lam/scada-project#28]
Khi add user có user_id tồn tại trong hệ thống, api trả về http_code: “500”, code: “10006”, message: “rpc error: code = Aborted desc = failed to endorse transaction, see attached details for more info”. Theo em thì nên trả về http_code: 400, message: "This user has existed"

**Comment by tran-the-lam** [comment]
https://github.com/tran-the-lam/scada-project/commit/eab4fa076a0495e18a5c58d090de5905803a243c 
Bạn check ở commit này nhé
