### ISSUE TITLE
Update password: nhập sai old_password

### ISSUE THREAD

**Issue by HPM6789** [tran-the-lam/scada-project#29]
Khi nhập sai old_password, api trả về http_code: “500”, code: “10006”, message: “rpc error: code = Aborted desc = failed to endorse transaction, see attached details for more info”. Theo em nên trả về http_code: 400, và message: "old password is wrong"

**Comment by tran-the-lam** [comment]
Mình đã fix ở commit này. Bạn check lại giúp mình nhé: https://github.com/tran-the-lam/scada-project/commit/de97df2a1a9c93903a4b45ac728f93e106d162e5

**Comment by HPM6789** [comment]
bạn merge luôn vào main để mình pull cho tiện đc ko :v?

**Comment by tran-the-lam** [comment]
Mình merge rồi nhé
