### ISSUE TITLE
Get User List feature

### ISSUE THREAD

**Issue by HPM6789** [tran-the-lam/scada-project#31]
Bạn sửa lại cho mình 1 chút về api get users. 
(Thêm tham số status, nếu status = 1 thì get active users, nếu status = 0  thì get deleted user, nếu status = null thì get tất cả user trong hệ thống)

**Comment by tran-the-lam** [comment]
Bạn check code ở nhánh này nhé: https://github.com/tran-the-lam/scada-project/tree/feat/kc

**Comment by tran-the-lam** [comment]
status = -1 thì get all nhé

**Comment by HPM6789** [comment]
Mình test thì 3 giá trị của status ra kết quả như nhau (mình đã xóa user_id = 2)
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/213e9181-8bd7-4502-b3dd-5058abc28306)
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/c5398751-c178-418d-972b-5d694e933d05)
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/abc3355d-cc6b-47b1-af34-ee9ccfe51f3e)

**Comment by HPM6789** [comment]
Trong list user thì cái nào bị xóa bạn để status = 0
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/2a74717d-a42c-434c-a18f-6a332e3b66e5)

**Comment by HPM6789** [comment]
bạn sửa nốt 2 issue còn lại giúp mình nhé

**Comment by tran-the-lam** [comment]
Trong tuần này mình bận, khả năng là không xử lý được. Bạn contribute vào repo được không, có gì mình sẽ review code

**Comment by HPM6789** [comment]
đây bạn nhé
![image](https://github.com/tran-the-lam/scada-project/assets/92874221/037d23b2-0518-40a8-84b7-aa77e679c186)
